# Generated by Django 2.1 on 2018-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='violation',
            field=models.CharField(choices=[('RED_LINE', 'Red line parking')], max_length=10),
        ),
    ]
